DROP SEQUENCE TASK_ID_SEQ;
DROP SEQUENCE MEMBER_ID_SEQ;
DROP SEQUENCE PROJECT_ID_SEQ;

DROP TABLE MEMBER_CALENDAR_DATE
DROP TABLE CALENDAR_DATE
DROP TABLE TASK
DROP TABLE PROJECT_MEMBER
DROP TABLE MEMBER
DROP TABLE PROJECT